on:
  push:
  schedule:
    - cron: "37 13 * * 0"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f ./scripts/requirements.txt ]; then pip install -r ./scripts/requirements.txt; fi
      - name: Scrape magic
        run: |
          rm ./questions/questions.md ./questions/questions.json || :
          python3 ./scripts/scrape.py
          python3 ./scripts/scrape-json.py
      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add ./questions/questions.md ./questions/questions.json
          git commit -m "[bot]scrape-`date +%s`" || exit 0
          git push --force
